name: Publish Docker image

on:
  push:
    branches: ['develop']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{secrets.DOCKERHUB_TOKEN}}" | docker login -u "${{secrets.DOCKERHUB_USER_NAME}}" --password-stdin

      - name: Build docker file
        run: docker build . --file Dockerfile --tag "${{secrets.DOCKERHUB_USER_NAME}}"/um-auth-service:latest
